version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rdForApp"  
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  api:
    image: nguyengnol/moku-test-system:latest
    container_name: online-test-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=OnlineTestSystem;User Id=sa;Password=YourStrong!Passw0rdForApp;TrustServerCertificate=True
      - JWT__Secret=YourSuperSecretKey
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5000:8080"   # HTTP (5000 bên ngoài => 8080 trong container)
      - "5001:443"    # HTTPS (5001 bên ngoài => 443 trong container)
    volumes:
      - ./https:/https:ro
    restart: unless-stopped

volumes:
  sql_data:
